name: Swift Format Check

on:
  pull_request:
    branches: [main]

jobs:
  format-check:
    name: Swift Format Check
    runs-on: ubuntu-latest
    container: swift:6.1.0

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Swift Format
        run: |
          swift format --recursive --in-place --parallel Sources

      - name: Check for changes
        run: |
          if ! git diff --exit-code --quiet; then
            echo "::error::Swift format check failed - code is not properly formatted"
            git --no-pager diff
            exit 1
          else
            echo "Swift format check passed - code is properly formatted"
          fi
