name: Swift Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    name: Build and Test on Linux
    
    runs-on: ubuntu-latest
    container:
      image: swift:6.1.0
    
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build --product edge-agent
    - name: Find binary path
      id: get-binary
      run: |
        BIN_PATH=$(swift build --show-bin-path)
        echo "Build directory contents:"
        
        if [ -f "$BIN_PATH/edge-agent" ]; then
          echo "BINARY_PATH=$BIN_PATH/edge-agent" >> $GITHUB_ENV
          echo "Binary found at $BIN_PATH/edge-agent"
        else
          echo "Searching for binary recursively in $BIN_PATH"
          FOUND_PATH=$(find $BIN_PATH -name "edge-agent" -type f | head -n 1)
          if [ -n "$FOUND_PATH" ]; then
            echo "BINARY_PATH=$FOUND_PATH" >> $GITHUB_ENV
            echo "Binary found at $FOUND_PATH"
          else
            echo "::error::Binary not found in build directory"
            exit 1
          fi
        fi
    - name: Upload binary artifact
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: edge-agent-${{ matrix.os }}
        path: ${{ env.BINARY_PATH }}
        retention-days: 14
        if-no-files-found: error
    - name: Output download info
      run: |
        echo "::notice::Binary artifact uploaded with ID: ${{ steps.upload-artifact.outputs.artifact-id }}"
        echo "::notice::Download URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"


